import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import axios from 'axios';
import JsBarcode from 'jsbarcode';
import './styles.css';

axios.defaults.withCredentials = true;
axios.defaults.headers.common.Accept = 'application/json';

async function downloadCsv(path, filename){const r=await api.get(path,{responseType:'blob'});if(r.status>=300){throw new Error('Unable to export logs.')}const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}

const api = axios.create({
    baseURL: '/api',
    withCredentials: true,
    headers: { Accept: 'application/json' },
    validateStatus: status => status >= 200 && status < 500,
});

api.interceptors.request.use(config => {
    const token = localStorage.getItem('smart-gate-auth-token');
    if (token) config.headers.Authorization = `Bearer ${token}`;
    return config;
});

function useTheme() {
    const [dark, setDark] = useState(() => localStorage.getItem('smart-gate-theme') === 'dark');
    useEffect(() => {
        document.documentElement.dataset.theme = dark ? 'dark' : 'light';
        localStorage.setItem('smart-gate-theme', dark ? 'dark' : 'light');
    }, [dark]);
    return [dark, () => setDark(v => !v)];
}

function Shell({ children, onHome, user, onLogout, dashboard = false, menuItems = [] }) {
    const [dark, toggleTheme] = useTheme();
    return (
        <div className={`app-shell ${dashboard ? 'dashboard-shell' : ''}`}>
            <header className="topbar">
                <button className="brand" onClick={onHome} aria-label="Go to home">
                    <span className="brand-mark">G</span>
                    <span className="brand-name">Golden Homes</span>
                </button>
                <div className="topbar-actions">
                    {dashboard && user
                        ? <ControlCenter dark={dark} toggleTheme={toggleTheme} onLogout={onLogout}/>
                        : <ThemeSwitch dark={dark} toggleTheme={toggleTheme}/>}
                </div>
            </header>
            {children}
            <footer><span>Golden Homes 2026</span><a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank" rel="noopener noreferrer">KUN3H0/BISM4RCK 2026</a></footer>
        </div>
    );
}

function ThemeSwitch({dark,toggleTheme}) {
    return <button className="ios-switch-button" type="button" onClick={toggleTheme} aria-label={dark?'Switch to light mode':'Switch to dark mode'}>
        <span className={`ios-switch ${dark?'on':''}`}><span className="ios-switch-thumb">{dark?'☀':'☾'}</span></span>
        <span className="ios-switch-label">{dark?'Dark':'Light'}</span>
    </button>;
}

function ControlCenter({dark,toggleTheme,onLogout}) {
    const [open,setOpen]=useState(false);
    useEffect(()=>{const close=()=>setOpen(false);window.addEventListener('click',close);return()=>window.removeEventListener('click',close)},[]);
    return <div className="control-center" onClick={e=>e.stopPropagation()}>
        <button className="control-center-trigger" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label="Settings" title="Settings">⚙</button>
        {open&&<div className="control-center-popover">
            <div className="control-theme-row"><span>{dark?'Dark mode':'Light mode'}</span><span onClick={toggleTheme}><span className={`ios-switch ${dark?'on':''}`}><span className="ios-switch-thumb">{dark?'☀':'☾'}</span></span></span></div>
            <button onClick={onLogout}><span>↪</span>Logout</button>
        </div>}
    </div>;
}

function Modal({ title, children, onClose, wide = false }) {
    return (
        <div className="modal-backdrop" role="dialog" aria-modal="true" onMouseDown={e => e.target === e.currentTarget && onClose()}>
            <div className={`modal ${wide ? 'modal-wide' : ''}`}>
                <div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose}>×</button></div>
                {children}
            </div>
        </div>
    );
}

function Landing({ navigate }) {
    return (
        <Shell onHome={() => navigate('home')}>
            <section className="hero">
                <div className="hero-copy">
                    <p className="eyebrow">GOLDEN HOMES</p>
                    <h1>Welcome.</h1>
                    <p className="hero-text">Access the gate system, submit a guest request, or check an existing guest credential.</p>
                    <div className="button-grid">
                        <button className="primary action-button" onClick={() => navigate('login')}>Login</button>
                        <button className="secondary action-button" onClick={() => navigate('visitor')}>Guest</button>
                        <button className="secondary action-button" onClick={() => navigate('status')}>Check Status <span className="muted-label">(for guests)</span></button>
                    </div>
                </div>
            </section>
        </Shell>
    );
}

function Login({ navigate, onLogin }) {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [showPassword, setShowPassword] = useState(false);
    const [error, setError] = useState('');
    const [busy, setBusy] = useState(false);

    async function submit(e) {
        e.preventDefault(); setError(''); setBusy(true);
        try {
            const r = await api.post('/auth/login', { email, password });
            if (r.status >= 300 || !r.data?.ok) throw new Error(r.data?.message || 'Unable to sign in.');
            if (r.data?.token) localStorage.setItem('smart-gate-auth-token', r.data.token);
            onLogin(r.data.user);
        } catch (err) {
            setError(err.response?.data?.message || err.message || 'Invalid email or password.');
        } finally { setBusy(false); }
    }

    return (
        <Shell onHome={() => navigate('home')}>
            <section className="form-card narrow">
                <button className="back-link" onClick={() => navigate('home')}>← Back</button>
                <p className="eyebrow">ACCOUNT ACCESS</p><h1>Sign in</h1>
                <p className="muted">Use your Golden Homes account credentials.</p>
                {error && <div className="alert error">{error}</div>}
                <form onSubmit={submit} className="form-stack">
                    <label>Email<input type="email" autoComplete="username" value={email} onChange={e => setEmail(e.target.value)} required /></label>
                    <label>Password<div className="password-wrap"><input type={showPassword ? "text" : "password"} autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required /><button type="button" className="password-toggle" onClick={()=>setShowPassword(v=>!v)}>{showPassword?"Hide":"Show"}</button></div></label>
                    <button className="primary action-button" disabled={busy}>{busy ? 'Signing in…' : 'Login'}</button>
                </form>
            </section>
        </Shell>
    );
}

function Visitor({ navigate }) {
    const [form,setForm]=useState({phase:'',block_number:'',lot_number:'',household_letter:'',house_number:'',visitor_name:'',contact_number:'',purpose_of_visit:'',people_count:1,stay_days:1,vehicles:[{plate_number:'',vehicle_type:'car'}]});
    const [idFile,setIdFile]=useState(null),[result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
    const update=(k,v)=>setForm(f=>({...f,[k]:v}));
    const updateVehicle=(i,k,v)=>setForm(f=>({...f,vehicles:f.vehicles.map((a,n)=>n===i?{...a,[k]:v}:a)}));
    const addVehicle=()=>form.vehicles.length<10&&setForm(f=>({...f,vehicles:[...f.vehicles,{plate_number:'',vehicle_type:'car'}]}));
    const removeVehicle=i=>setForm(f=>({...f,vehicles:f.vehicles.filter((_,n)=>n!==i)}));
    async function submit(e){e.preventDefault();setError('');setBusy(true);try{const fd=new FormData();fd.append('phase',form.phase);fd.append('block_number',form.block_number);fd.append('lot_number',form.lot_number);fd.append('household_letter',form.household_letter);fd.append('house_number',`${form.block_number}-${form.lot_number}-${form.household_letter}`);fd.append('visitor_name',form.visitor_name);fd.append('contact_number',form.contact_number);fd.append('purpose_of_visit',form.purpose_of_visit);fd.append('people_count',String(form.people_count));fd.append('stay_days',String(form.stay_days));form.vehicles.forEach((v,i)=>{fd.append(`vehicles[${i}][plate_number]`,v.plate_number.toUpperCase());fd.append(`vehicles[${i}][vehicle_type]`,v.vehicle_type)});if(idFile)fd.append('government_id',idFile);const r=await api.post('/visitor',fd);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to submit.');setResult(r.data)}catch(err){setError(err.response?.data?.message||err.message||'Unable to submit the guest request.')}finally{setBusy(false)}}
    if(result) return <Shell onHome={()=>navigate('home')}><section className="form-card guest-success"><p className="eyebrow">REQUEST SUBMITTED</p><h1>You're all set.</h1><p className="muted">The resident must approve this guest request before entry.</p><div className="credential"><span>Guest barcode</span><strong>{result.visitor_id}</strong><Barcode value={result.visitor_id}/><small className="muted">Keep this Code 128 barcode for the gate.</small></div><div className="button-row"><button className="primary action-button" onClick={()=>navigate('status')}>Check Status</button><button className="secondary action-button" onClick={()=>navigate('home')}>Done</button></div></section></Shell>;
    return <Shell onHome={()=>navigate('home')}><section className="form-card guest-form"><button className="back-link" onClick={()=>navigate('home')}>← Back</button><p className="eyebrow">GUEST ACCESS</p><h1>Guest request</h1><p className="muted">Enter your details. The resident will review your request.</p>{error&&<div className="alert error">{error}</div>}<form onSubmit={submit} className="form-stack"><div className="form-grid">
        <label>Resident phase<input value={form.phase} onChange={e=>update('phase',e.target.value)} placeholder="1" required /></label>
        <label>Block<input value={form.block_number} onChange={e=>update('block_number',e.target.value.replace(/[^0-9A-Za-z]/g,''))} required /></label>
        <label>Lot<input value={form.lot_number} onChange={e=>update('lot_number',e.target.value.replace(/[^0-9A-Za-z]/g,''))} required /></label>
        <label>Letter<input value={form.household_letter} maxLength={1} onChange={e=>update('household_letter',e.target.value.replace(/[^A-Za-z]/g,'').toUpperCase())} required /></label>
        <label>Guest name<input value={form.visitor_name} onChange={e=>update('visitor_name',e.target.value)} required /></label>
        <label>Contact number<input value={form.contact_number} onChange={e=>update('contact_number',e.target.value)} /></label>
        <label>How many days are you staying?<input type="number" min="1" max="30" value={form.stay_days} onChange={e=>update('stay_days',Number(e.target.value))} required /></label><label>People count<input type="number" min="1" max="20" value={form.people_count} onChange={e=>update('people_count',Number(e.target.value))} required /></label>
        <label className="full-width">Purpose of visit<input value={form.purpose_of_visit} onChange={e=>update('purpose_of_visit',e.target.value)} required /></label>
        <div className="full-width"><div className="panel-head"><div><h3>Vehicles</h3><p className="muted">Add up to 10 vehicles. The barcode stays valid for the number of days you choose.</p></div><button type="button" className="secondary compact" onClick={addVehicle} disabled={form.vehicles.length>=10}>Add vehicle</button></div>{form.vehicles.map((v,i)=><div className="vehicle-row" key={i}><input placeholder="Plate number" value={v.plate_number} onChange={e=>updateVehicle(i,'plate_number',e.target.value.toUpperCase())} required/><select value={v.vehicle_type} onChange={e=>updateVehicle(i,'vehicle_type',e.target.value)}><option>car</option><option>motorcycle</option><option>truck</option><option>tricycle</option><option>ebike</option><option>other</option></select>{i>0&&<button type="button" className="text-button" onClick={()=>removeVehicle(i)}>Remove</button>}</div>)}</div>
        <label className="full-width">Government ID (optional)<input type="file" accept=".jpg,.jpeg,.png,.pdf" onChange={e=>setIdFile(e.target.files?.[0]||null)}/><small className="muted">You may continue without uploading an ID.</small></label>
    </div><button className="primary action-button" disabled={busy}>{busy?'Submitting…':'Submit Guest Request'}</button></form></section></Shell>;
}

function VisitorStatus({navigate}) {
    const [credential,setCredential]=useState(''),[result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
    async function check(e){e.preventDefault();setError('');setResult(null);setBusy(true);try{const v=credential.trim().toUpperCase();const r=await api.get(`/visitor/${encodeURIComponent(v)}`);if(r.status>=300||!r.data?.ok)throw new Error(r.status===404?'No guest request was found for that credential.':'Unable to check status.');setResult(r.data)}catch(err){setError(err.response?.data?.message||err.message||'Unable to check status.')}finally{setBusy(false)}}
    return <Shell onHome={()=>navigate('home')}><section className="form-card narrow"><button className="back-link" onClick={()=>navigate('home')}>← Back</button><p className="eyebrow">GUEST STATUS</p><h1>Check status</h1><p className="muted">Enter the six-character credential you received.</p>{error&&<div className="alert error">{error}</div>}<form onSubmit={check} className="form-stack"><label>Guest credential<input value={credential} onChange={e=>setCredential(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6))} placeholder="ABC123" maxLength={6} required /></label><button className="primary action-button" disabled={busy}>{busy?'Checking…':'Check Status'}</button></form>{result&&<div className={`status-card ${String(result.status).toLowerCase()}`}><span>REQUEST STATUS</span><strong>{String(result.status).replace('_',' ').toUpperCase()}</strong><small>Credential: {result.visitor_id}</small></div>}</section></Shell>;
}

const navFor = (role, isSuperAdmin = false) => role === 'guard'
    ? [{id:'overview',icon:'⌂',label:'Overview'},{id:'logs',icon:'▤',label:'Gate Logs'},{id:'walkins',icon:'＋',label:'Walk-in Guests'},{id:'blacklist',icon:'⊘',label:'Blacklist'},{id:'notifications',icon:'●',label:'Notifications'},{id:'incidents',icon:'⚠',label:'Incident Center'},{id:'settings',icon:'⚙',label:'Settings'}]
    : role === 'admin'
        ? [{id:'overview',icon:'⌂',label:'Overview'},{id:'logs',icon:'▤',label:'Gate Logs'},{id:'account-logs',icon:'◷',label:'Account Logs'},{id:'blacklist',icon:'⊘',label:'Blacklist'},{id:'accounts',icon:'♙',label:'Accounts'},{id:'vehicles',icon:'▣',label:'Vehicles'},{id:'rfid',icon:'◉',label:'RFID Cards'},{id:'system-health',icon:'⌁',label:'System Health'},...(isSuperAdmin?[{id:'statistics',icon:'▥',label:'Statistics'},{id:'backup',icon:'⇅',label:'Backup / Restore'}]:[]),{id:'notifications',icon:'●',label:'Notifications'},{id:'incidents',icon:'⚠',label:'Incident Center'},{id:'settings',icon:'⚙',label:'Settings'}]
        : [{id:'overview',icon:'⌂',label:'Overview'},{id:'vehicles',icon:'▣',label:'My Vehicles'},{id:'guest-history',icon:'◷',label:'Guest History'},{id:'notifications',icon:'●',label:'Notifications'},{id:'settings',icon:'⚙',label:'Settings'}];

function Sidebar({user,active,setActive,collapsed,setCollapsed}) {
    const nav=navFor(user.role);
    return <aside className={`sidebar ${collapsed?'is-collapsed':''}`}><div className="sidebar-head"><span className="sidebar-title">{user.role === 'admin'?'Administration':user.role === 'guard'?'Guard Console':'Resident'}</span><button className="icon-button sidebar-collapse" onClick={()=>{setCollapsed(v=>{const next=!v;localStorage.setItem('smart-gate-sidebar',next?'mini':'full');return next})}} title={collapsed?'Expand sidebar':'Minimize sidebar'}>{collapsed?'›':'‹'}</button></div><nav>{nav.map(item=><button key={item.id} className={active===item.id?'active':''} title={item.label} onClick={()=>setActive(item.id)}><span className="nav-icon">{item.icon}</span><span className="nav-label">{item.label}</span></button>)}</nav></aside>;
}

function ReaderPills({readers=[]}) { const by=Object.fromEntries(readers.map(r=>[r.reader,r])); return <div className="reader-row"><ReaderPill name="Entry RFID" reader={by.entry}/><ReaderPill name="Exit RFID" reader={by.exit}/></div>; }
function ReaderPill({name,reader}){const online=!!reader?.online;return <div className={`reader-pill ${online?'online':'offline'}`}><span className="dot"/><span><strong>{name}</strong><small>{reader?.last_seen_at?`Last heartbeat ${manilaTime(reader.last_seen_at)}`:'No heartbeat yet'}</small></span><strong>{online?'Online':'Offline'}</strong></div>}
function Stat({label,value,sub}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function manilaTime(value){if(!value)return '—';try{let raw=String(value);let d=/Z$|[+-]\d\d:\d\d$/.test(raw)?new Date(raw):new Date(raw.replace(' ','T')+'+08:00');return new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',dateStyle:'medium',timeStyle:'medium'}).format(d)}catch{return String(value)}}

function LogFilters({filters,setFilters,account=false}){
    return <div className="log-filters">
        <select value={filters.gate} onChange={e=>setFilters(f=>({...f,gate:e.target.value}))}><option value="all">All gates</option><option value="entry">Entry</option><option value="exit">Exit</option></select>
        {!account&&<select value={filters.result} onChange={e=>setFilters(f=>({...f,result:e.target.value}))}><option value="all">All results</option><option value="approved">Approved</option><option value="denied">Denied</option><option value="manual_override">Override</option></select>}
        <select value={filters.type} onChange={e=>setFilters(f=>({...f,type:e.target.value}))}><option value="all">All actions</option>{account?<><option value="login">Login</option><option value="logout">Logout</option><option value="add_vehicle">Add vehicle</option><option value="remove_vehicle">Remove vehicle</option><option value="gate_override_requested">Gate override</option><option value="gate_override_acknowledged">Override acknowledged</option><option value="add_blacklist">Add blacklist</option><option value="visitor_barcode_scan">Guest scan</option><option value="approve_visitor">Approve guest</option><option value="reject_visitor">Reject guest</option></>:<><option value="rfid_scan">RFID scan</option><option value="visitor_barcode_scan">Guest barcode</option><option value="manual_override">Gate override</option></>}</select>
    </div>
}

function filterLogs(logs,filters){return logs.filter(x=>(filters.gate==='all'||x.reader===filters.gate)&&(filters.result==='all'||x.gate_status===filters.result)&&(filters.type==='all'||x.event_type===filters.type));}
function paginate(items,page,pageSize){const start=(page-1)*pageSize;return items.slice(start,start+pageSize)}
function Pagination({page,total,pageSize=50,onPage}){const pages=Math.max(1,Math.ceil(total/pageSize));if(pages<=1)return null;return <div className="pagination"><button className="secondary compact" disabled={page<=1} onClick={()=>onPage(page-1)}>Previous</button><span>Page {page} of {pages}</span><button className="secondary compact" disabled={page>=pages} onClick={()=>onPage(page+1)}>Next</button></div>}
function LogTable({logs}){return <div className="table-wrap"><table><thead><tr><th>Time (GMT+8)</th><th>Gate</th><th>Account / Guest</th><th>Plate</th><th>Type</th><th>Result</th></tr></thead><tbody>{logs.length?logs.map(log=><tr key={log.id}><td>{manilaTime(log.created_at)}</td><td>{(log.reader||'—').toUpperCase()}</td><td>{log.account_name||log.actor_name||log.account_email||log.log_notes||'Guest'}</td><td>{log.plate_number||'—'}</td><td>{String(log.event_type||'').replaceAll('_',' ')}</td><td><span className={`badge ${log.gate_status}`}>{log.gate_status}</span></td></tr>):<tr><td colSpan="6" className="empty">No matching gate logs.</td></tr>}</tbody></table></div>}

function InlineOverride({user,onModal}){return <section className="panel inline-override"><PanelHead title="Emergency gate override" subtitle="Emergency opening requires acknowledgement before the ESP32 receives the command."/><div className="override-grid"><button className="danger large-control" onClick={()=>onModal('override-entry')}>Open Entry Gate</button><button className="danger large-control" onClick={()=>onModal('override-exit')}>Open Exit Gate</button></div></section>}
function GateAnimation({gate,state='closed',readerOnline}){
    return <div className={`gate-card ${state}`}><div className="gate-card-head"><div><span className="eyebrow">{gate.toUpperCase()} GATE</span><h3>{state==='open'?'OPEN':state==='opening'?'OPENING':'CLOSED'}</h3></div><span className={`mini-status ${readerOnline?'online':'offline'}`}>{readerOnline?'Reader online':'Reader offline'}</span></div><div className="gate-scene"><div className="gate-road"/><div className="gate-arm"/><div className="gate-post"/><div className="gate-light"/></div><small>{state==='open'?'Gate open activity detected.':state==='opening'?'Opening command active.':'Ready for access.'}</small></div>
}
function GateAnimations({readers,states}){const by=Object.fromEntries((readers||[]).map(r=>[r.reader,r]));return <div className="gate-grid"><GateAnimation gate="entry" state={states.entry} readerOnline={!!by.entry?.online}/><GateAnimation gate="exit" state={states.exit} readerOnline={!!by.exit?.online}/></div>}

function NotificationCenter({user}){
    const [items,setItems]=useState([]),[error,setError]=useState('');
    async function load(){try{const r=user.role==='resident'?await api.get('/resident/notifications'):await api.get('/staff/alerts');if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to load notifications.');setItems(r.data.notifications||r.data.alerts||[])}catch(e){setError(e.response?.data?.message||e.message)}}
    useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
    async function dismiss(x){if(user.role==='resident')await api.post(`/resident/notifications/${x.id}/read`);setItems(a=>a.filter(i=>i.id!==x.id))}
    return <section className="panel"><PanelHead title="Notifications" subtitle="Recent account and gate activity."/>{error&&<div className="alert error">{error}</div>}<div className="notification-list">{items.length?items.map(x=><div className="notification-card" key={x.id}><div><strong>{x.title||'Blacklist alert'}</strong><p>{x.message||`${String(x.reader||'').toUpperCase()} gate denied access: ${x.log_notes||'Blacklist match detected.'}`}</p><small>{manilaTime(x.created_at)}</small></div><button className="icon-button" aria-label="Close notification" onClick={()=>dismiss(x)}>×</button></div>):<div className="empty">No new notifications.</div>}</div></section>
}
function SystemHealth({user}){
    const [data,setData]=useState(null),[devices,setDevices]=useState([]),[error,setError]=useState('');
    async function load(){try{const r=await api.get('/admin/system-health');if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to load system health.');setData(r.data);if(user.is_super_admin){const d=await api.get('/admin/device-management');if(d.status<300&&d.data?.ok)setDevices(d.data.devices||[])}}catch(e){setError(e.response?.data?.message||e.message)}}
    useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
    async function restart(deviceId){if(!window.confirm(`Restart device ${deviceId}?`))return;const r=await api.post('/admin/device-management/restart',{device_id:deviceId});if(r.status>=300)alert(r.data?.message||'Unable to queue restart.');else alert('Restart command queued.')}
    return <section className="panel"><PanelHead title="System health" subtitle="Admin-only status for the gate stack, MQTT, RFID readers and tunnel configuration."/>{error&&<div className="alert error">{error}</div>}<div className="health-grid">{data&&Object.entries(data.services).map(([key,v])=><div className="health-card" key={key}><span>{key.replaceAll('_',' ')}</span><strong className={`badge ${v.status==='online'?'online':v.status==='offline'?'offline':'active'}`}>{v.status}</strong>{v.host&&<small>{v.host}:{v.port}</small>}{v.readers&&<small>{v.readers.map(r=>`${r.reader}: ${r.online?'online':'offline'}`).join(' · ')}</small>}</div>)}</div>{user.is_super_admin&&<><PanelHead title="ESP32 diagnostics" subtitle="Super admin only — live device telemetry."/><div className="device-list">{devices.length?devices.map(d=><div className="device-card" key={d.reader}><div><strong>{String(d.reader).toUpperCase()} reader · {d.online?'ONLINE':'OFFLINE'}</strong><small>Device: {d.device_id||'—'} · Firmware: {d.firmware_version||'—'} · IP: {d.ip_address||'—'}</small><small>Wi-Fi: {d.wifi_status||'—'} · RSSI: {d.wifi_rssi??'—'} dBm · Free heap: {d.free_heap??'—'} bytes</small><small>Uptime: {d.uptime_seconds??'—'}s · MQTT: {d.mqtt_status||'—'} · Last heartbeat: {d.last_seen_at?manilaTime(d.last_seen_at):'—'}</small></div><button className="danger compact" disabled={!d.device_id} onClick={()=>restart(d.device_id)}>Restart</button></div>):<div className="empty">No ESP32 heartbeat records yet.</div>}</div></>}{data&&<small className="muted">Last checked {manilaTime(data.checked_at)}</small>}</section>
}

function IncidentCenter(){
    const [data,setData]=useState({incidents:[],reader_incidents:[]}),[error,setError]=useState('');
    async function load(){try{const r=await api.get('/staff/incidents');if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to load incidents.');setData(r.data)}catch(e){setError(e.response?.data?.message||e.message)}}
    useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
    return <section className="panel"><PanelHead title="Gate incident center" subtitle="Blacklist hits, denied access, overrides and reader outages."/>{error&&<div className="alert error">{error}</div>}{data.reader_incidents?.map(r=><div className="alert error" key={'r'+r.id}><strong>{String(r.reader).toUpperCase()} RFID reader offline</strong><span>Last heartbeat: {r.last_seen_at?manilaTime(r.last_seen_at):'Never'}</span></div>)}<div className="table-wrap"><table><thead><tr><th>Time</th><th>Gate</th><th>Incident</th><th>Plate</th><th>Account</th><th>Notes</th></tr></thead><tbody>{data.incidents.length?data.incidents.map(x=><tr key={x.id}><td>{manilaTime(x.created_at)}</td><td>{String(x.reader||'—').toUpperCase()}</td><td>{String(x.event_type||'').replaceAll('_',' ')}</td><td>{x.plate_number||'—'}</td><td>{x.account_name||'—'}</td><td>{x.log_notes||'—'}</td></tr>):<tr><td colSpan="6" className="empty">No incidents.</td></tr>}</tbody></table></div></section>
}
function AdminStatsPanel({stats}){return <section className="panel"><PanelHead title="Gate statistics" subtitle="Super admin analytics — last 7 days."/><div className="stats"><Stat label="Approved today" value={stats.today?.approved||0}/><Stat label="Denied today" value={stats.today?.denied||0}/><Stat label="Guest requests today" value={stats.today?.guests||0}/>{(stats.by_gate||[]).map(g=><Stat key={g.reader} label={`${String(g.reader).toUpperCase()} events (7d)`} value={g.total}/>)}</div><div className="chart-list">{(stats.weekly||[]).map(x=>{const max=Math.max(1,...(stats.weekly||[]).flatMap(d=>[Number(d.approved||0),Number(d.denied||0)]));return <div className="chart-row" key={x.day}><span>{x.day}</span><div className="chart-bars"><i className="bar approved" style={{width:`${Math.round(Number(x.approved||0)/max*100)}%`}} title={`Approved ${x.approved}`}/><i className="bar denied" style={{width:`${Math.round(Number(x.denied||0)/max*100)}%`}} title={`Denied ${x.denied}`}/></div><small>{x.approved} / {x.denied}</small></div>})}</div></section>}
function SuperAdminStats(){const [stats,setStats]=useState(null);useEffect(()=>{api.get('/staff/stats').then(r=>r.data?.ok&&setStats(r.data))},[]);return stats?<AdminStatsPanel stats={stats}/>:<section className="panel"><PanelHead title="Gate statistics" subtitle="Loading…"/></section>}
function BackupCenter(){const [busy,setBusy]=useState(false),[file,setFile]=useState(null),[message,setMessage]=useState('');async function backup(){setBusy(true);setMessage('');try{await downloadCsv('/admin/backup','smart-gate-backup.sql');setMessage('Backup downloaded.')}catch(e){setMessage(e.message||'Backup failed.')}finally{setBusy(false)}}async function restore(){if(!file||!window.confirm('Restore this database backup? This can replace current data. Make sure you have a fresh backup first.'))return;setBusy(true);setMessage('');try{const fd=new FormData();fd.append('backup',file);const r=await api.post('/admin/backup/restore',fd);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Restore failed.');setMessage('Database restore completed. Reload the dashboard.')}catch(e){setMessage(e.response?.data?.message||e.message||'Restore failed.')}finally{setBusy(false)}}return <section className="panel"><PanelHead title="Backup / Restore" subtitle="Super admin only. Database backups contain the full Smart Gate database."/>{message&&<div className="alert">{message}</div>}<div className="feature-grid"><div className="feature-card"><h3>Download backup</h3><p>Export the current database as a SQL backup.</p><button className="primary" disabled={busy} onClick={backup}>Download SQL backup</button></div><div className="feature-card"><h3>Restore backup</h3><p>Restore a previously exported Smart Gate SQL backup.</p><input type="file" accept=".sql,.txt" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="danger" disabled={busy||!file} onClick={restore}>Restore database</button></div></div></section>}

function StaffDashboard({user,onLogout}) {
    const [active,setActive]=useState('overview'),[collapsed,setCollapsed]=useState(() => localStorage.getItem('smart-gate-sidebar') === 'mini'),[data,setData]=useState({readers:[],recent_logs:[]}),[logs,setLogs]=useState([]),[error,setError]=useState(''),[modal,setModal]=useState(null),[rfidEvent,setRfidEvent]=useState(null),[states,setStates]=useState({entry:'closed',exit:'closed'}),[accountLogs,setAccountLogs]=useState([]);
    const lastIdRef=useRef(0); const timers=useRef({entry:null,exit:null});
    const [alerts,setAlerts]=useState([]),[dismissedAlerts,setDismissedAlerts]=useState(()=>new Set()),[blacklist,setBlacklist]=useState([]),[walkins,setWalkins]=useState([]),[users,setUsers]=useState([]),[vehicles,setVehicles]=useState([]),[cards,setCards]=useState([]),[stats,setStats]=useState(null);
    const [filters,setFilters]=useState({gate:'all',result:'all',type:'all'}),[accountFilters,setAccountFilters]=useState({gate:'all',result:'all',type:'all'}),[logPage,setLogPage]=useState(1),[accountLogPage,setAccountLogPage]=useState(1);

    async function loadAlerts(){const r=await api.get('/staff/alerts');if(r.data?.ok)setAlerts(r.data.alerts||[])}
    async function loadOverview(initial=false){const r=await api.get('/staff/overview');if(r.status>=300||!r.data?.ok){setError(r.data?.message||'Unable to load dashboard.');return}setData(r.data);if(initial){const seed=r.data.recent_logs||[];setLogs(seed);lastIdRef.current=Math.max(0,...seed.map(x=>x.id));}}
    function animateGate(gate){setStates(s=>({...s,[gate]:'opening'}));setTimeout(()=>setStates(s=>({...s,[gate]:'open'})),180);clearTimeout(timers.current[gate]);timers.current[gate]=setTimeout(()=>setStates(s=>({...s,[gate]:'closed'})),3200);}
    async function pollLogs(){const r=await api.get(`/staff/logs?after_id=${lastIdRef.current}&limit=50`);if(r.status>=300||!r.data?.ok)return;const fresh=r.data.logs||[];if(!fresh.length)return;const ordered=[...fresh].sort((a,b)=>a.id-b.id);setLogs(prev=>[...ordered,...prev].slice(0,300));lastIdRef.current=Math.max(lastIdRef.current,...ordered.map(x=>x.id));ordered.forEach(ev=>{if(ev.reader&&(['approved','manual_override'].includes(ev.gate_status)||ev.event_type==='visitor_barcode_scan'))animateGate(ev.reader);if(ev.event_type==='rfid_scan')setRfidEvent(ev);});}
    async function loadLists(){const b=await api.get('/staff/blacklist');if(b.data?.ok)setBlacklist(b.data.items||[]);if(user.role==='guard'){const w=await api.get('/staff/walkins');if(w.data?.ok)setWalkins(w.data.items||[]);}if(user.role==='admin'){const [u,v,c,a,st]=await Promise.all([api.get('/admin/users'),api.get('/admin/vehicles'),api.get('/admin/rfid-cards'),api.get('/admin/account-logs'),api.get('/staff/stats')]);if(u.data?.ok)setUsers(u.data.users||[]);if(v.data?.ok)setVehicles(v.data.vehicles||[]);if(c.data?.ok)setCards(c.data.cards||[]);if(a.data?.ok)setAccountLogs(a.data.logs||[]);if(st.data?.ok)setStats(st.data);}}
    useEffect(()=>{loadOverview(true);loadLists();loadAlerts();const timer=setInterval(()=>{loadOverview(false);pollLogs();loadAlerts();if(user.role==='admin')api.get('/admin/account-logs').then(r=>r.data?.ok&&setAccountLogs(r.data.logs||[]));},2500);return()=>{clearInterval(timer);Object.values(timers.current).forEach(clearTimeout)}},[]);
    async function logout(){try{await api.post('/auth/logout')}finally{onLogout()}}
    const currentLogs=logs.length?logs:(data.recent_logs||[]); const filtered=filterLogs(currentLogs,filters); const logPageItems=paginate(filtered,logPage,50); const filteredAccountLogs=filterLogs(accountLogs,{...accountFilters,gate:'all',result:'all'}); const accountLogPageItems=paginate(filteredAccountLogs,accountLogPage,50);
    const nav=navFor(user.role,user.is_super_admin); const menuItems=nav.map(i=>({...i,onClick:()=>setActive(i.id)}));
    const content={
        overview:<Overview user={user} data={data} logs={currentLogs.slice(0,10)} onAction={setActive} onModal={setModal} states={states} stats={stats}/>,
        logs:<section className="panel"><PanelHead title="Gate logs" subtitle="Live entry and exit activity. Updates automatically." action={<div className="button-row compact-row"><button className="secondary compact" onClick={()=>downloadCsv('/staff/export-gate-logs','smart-gate-gate-logs.csv').catch(e=>alert(e.message))}>Export CSV</button>{user.is_super_admin&&<button className="danger compact" onClick={async()=>{if(window.confirm('Delete all gate logs?')){await api.delete('/admin/gate-logs');setLogs([]);loadOverview(true)}}}>Delete all logs</button>}</div>}/><LogFilters filters={filters} setFilters={f=>{setFilters(f);setLogPage(1)}}/><LogTable logs={logPageItems}/><Pagination page={logPage} total={filtered.length} pageSize={50} onPage={setLogPage}/></section>,
        'visitor-scan':user.role==='guard'?<section className="panel"><PanelHead title="Guest barcode" subtitle="Scan a real barcode and select the gate in a popup."/><FeatureCard title="Scan guest barcode" text="Camera scanner with entry/exit selection. No QR scanner." button="Open scanner" onClick={()=>setModal('visitor-scan')}/></section>:null,
        walkins:user.role==='guard'?<WalkInPanel items={walkins} onAdd={()=>setModal('walkin')} />:null,
        blacklist:<BlacklistPanel items={blacklist} onAdd={()=>setModal('blacklist')} onRemove={async id=>{await api.delete(`/staff/blacklist/${id}`);loadLists()}}/>,
        
        accounts:<AdminAccounts/>, vehicles:<AdminVehicles/>, rfid:<AdminRfid cards={cards}/>,
        'system-health':user.role==='admin'?<SystemHealth user={user}/>:null,
        statistics:user.is_super_admin?<SuperAdminStats/>:null,
        backup:user.is_super_admin?<BackupCenter/>:null,
        notifications:<NotificationCenter user={user}/>,
        incidents:<IncidentCenter/>,
        'override-entry':<section className="panel"><PanelHead title="Emergency gate override" subtitle="Emergency controls are available directly from Overview."/><OverridePanel onOpen={gate=>setModal('override-'+gate)}/></section>,
        'override-exit':<section className="panel"><PanelHead title="Emergency gate override" subtitle="Emergency controls are available directly from Overview."/><OverridePanel onOpen={gate=>setModal('override-'+gate)}/></section>,
        settings:<AccountSettings/>,
        'account-logs':<section className="panel"><PanelHead title="Account logs" subtitle="Resident and staff account activity are shown separately — Manila time (GMT+8)." action={<div className="button-row compact-row"><button className="secondary compact" onClick={()=>downloadCsv('/admin/export-account-logs','smart-gate-account-logs.csv').catch(e=>alert(e.message))}>Export CSV</button>{user.is_super_admin&&<button className="danger compact" onClick={async()=>{if(window.confirm('Delete all account logs?')){await api.delete('/admin/account-logs');setAccountLogs([])}}}>Delete all logs</button>}</div>}/><div className="log-section"><h3 className="section-title">Resident account logs</h3><AccountLogTable logs={accountLogs.filter(x=>x.role==='resident')}/></div><div className="log-section"><h3 className="section-title">Staff account logs</h3><AccountLogTable logs={accountLogs.filter(x=>['guard','admin'].includes(x.role))}/></div></section>,
    };
    return <Shell dashboard user={user} onHome={()=>setActive('overview')} onLogout={logout} menuItems={menuItems}><Sidebar user={user} active={active} setActive={setActive} collapsed={collapsed} setCollapsed={setCollapsed}/><main className={`dashboard-page ${collapsed ? 'sidebar-collapsed' : ''}`}><div className="mobile-sticky-nav">{nav.map(i=><button key={i.id} className={active===i.id?'active':''} onClick={()=>setActive(i.id)}><span>{i.icon}</span><small>{i.label}</small></button>)}</div><div className="dashboard-content">{alerts.filter(a=>!dismissedAlerts.has(a.id)).map(a=><div className="alert blacklist-alert" key={a.id}><div><strong>BLACKLIST ALERT</strong><span>{String(a.reader||'').toUpperCase()} gate denied access{a.plate_number?' for '+a.plate_number:''}. {a.log_notes||''}</span><small>{manilaTime(a.created_at)}</small></div><button className="icon-button" onClick={()=>setDismissedAlerts(prev=>new Set([...prev,a.id]))} aria-label="Close alert">×</button></div>)}{error&&<div className="alert error">{error}</div>}{content[active]||content.overview}</div></main>{modal==='visitor-scan'&&<VisitorScanModal onClose={()=>setModal(null)} onDone={()=>{setModal(null);pollLogs()}}/>}{modal==='walkin'&&<WalkInModal onClose={()=>setModal(null)} onDone={()=>{setModal(null);loadLists()}}/>}{modal==='blacklist'&&<BlacklistModal onClose={()=>setModal(null)} onDone={()=>{setModal(null);loadLists()}}/>}{modal?.startsWith('override-')&&<OverrideModal gate={modal.split('-')[1]} onClose={()=>setModal(null)} onDone={(gate)=>{setModal(null);animateGate(gate);loadOverview(false);pollLogs()}}/>}{rfidEvent&&<RfidPopup event={rfidEvent} onClose={()=>setRfidEvent(null)}/>}</Shell>;
}

function PanelHead({title,subtitle,action}){return <div className="panel-head"><div><h2>{title}</h2><p className="muted">{subtitle}</p></div>{action}</div>}
function Overview({user,data,logs,onAction,onModal,states,stats}){return <><section className="dashboard-head"><div><p className="eyebrow">{user.role==='admin'?'ADMIN DASHBOARD':'GUARD DASHBOARD'}</p><h1>Welcome, {user.full_name}</h1><p className="muted">{user.email}</p></div></section><ReaderPills readers={data.readers}/>{user.role==='guard'&&<section className="panel guest-scan-overview"><PanelHead title="Guest scan" subtitle="Scan a guest's Code 128 barcode with the USB barcode scanner. QR codes are not supported."/><button className="primary large-control" onClick={()=>onModal('visitor-scan')}>Scan guest barcode</button></section>}<InlineOverride user={user} onModal={onModal}/><GateAnimations readers={data.readers} states={states}/><div className="stats"><Stat label="Recent gate logs" value={logs.length}/><Stat label="Active blacklist" value={data.blacklist_count||0}/>{user.role==='guard'&&<Stat label="Walk-in guests" value={data.walk_in_count||0}/>}</div>{user.is_super_admin&&stats&&<AdminStatsPanel stats={stats}/>}<section className="panel"><PanelHead title="Recent entry & exit logs" subtitle="The latest ten gate events update automatically." action={<button className="secondary compact" onClick={()=>onAction('logs')}>All logs</button>}/><LogTable logs={logs}/></section><section className="feature-grid">{user.role==='guard'&&<FeatureCard title="Walk-in guest" text="Create a temporary guest credential from the dashboard." button="Add walk-in" onClick={()=>onAction('walkins')}/>} <FeatureCard title="Blacklist" text="Block a guest or vehicle from entry." button="Manage blacklist" onClick={()=>onAction('blacklist')}/>{user.role==='admin'&&<FeatureCard title="Account logs" text="Review resident and staff login and action history." button="View account logs" onClick={()=>onAction('account-logs')}/>}</section></>}
function FeatureCard({title,text,button,onClick}){return <div className="feature-card"><h3>{title}</h3><p>{text}</p><button className="secondary" onClick={onClick}>{button}</button></div>}

function Barcode({value}){const ref=useRef(null);useEffect(()=>{if(ref.current&&value){try{JsBarcode(ref.current,value,{format:'CODE128',displayValue:true,height:64,margin:8,lineColor:'currentColor',background:'transparent'})}catch{}}},[value]);return <svg ref={ref} className="barcode" aria-label={`Barcode ${value}`}/>}

function VisitorScanModal({onClose,onDone}){
    const [gate,setGate]=useState('entry'),[credential,setCredential]=useState(''),[error,setError]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false);
    const input=useRef(null);
    useEffect(()=>{input.current?.focus()},[]);
    async function submit(e){e?.preventDefault();const value=credential.trim().toUpperCase();if(!value)return;setError('');setBusy(true);try{const r=await api.post('/staff/visitor-scan',{credential:value,gate});if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Scan failed.');setResult(r.data);setCredential('');onDone();}catch(e){setError(e.response?.data?.message||e.message||'Scan failed.');input.current?.focus()}finally{setBusy(false)}}
    return <Modal title="Scan guest barcode" onClose={onClose}><p className="muted">Use the USB barcode scanner. It reads Code 128 barcodes only; QR codes are not supported.</p><div className="segmented"><button type="button" className={gate==='entry'?'selected':''} onClick={()=>setGate('entry')}>Entry gate</button><button type="button" className={gate==='exit'?'selected':''} onClick={()=>setGate('exit')}>Exit gate</button></div>{error&&<div className="alert error">{error}</div>}<form className="form-stack" onSubmit={submit}><label>Barcode value<input ref={input} autoComplete="off" autoFocus value={credential} onChange={e=>setCredential(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();submit(e)}}} placeholder="Scan Code 128 barcode" required/></label><button className="primary" disabled={busy||!credential.trim()}>{busy?'Checking…':'Check guest'}</button></form>{result&&<div className={`scan-result ${result.gate_status}`}><span>{result.gate.toUpperCase()} GATE</span><strong>{result.gate_opened?'GATE OPENED':'ACCESS DENIED'}</strong><span>{result.guest?.name||'Unknown guest'} · {result.guest?.plate_number||'No plate'}</span><small>{result.reason}</small></div>}</Modal>
}

function WalkInModal({onClose,onDone}){const [f,setF]=useState({visitor_name:'',contact_number:'',purpose_of_visit:'',plate_number:'',vehicle_type:'car',people_count:1}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[created,setCreated]=useState(null);const u=(k,v)=>setF(x=>({...x,[k]:v}));async function submit(e){e.preventDefault();setBusy(true);try{const r=await api.post('/staff/walkins',f);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to create walk-in.');setCreated(r.data)}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}return <Modal title="Add walk-in guest" onClose={onClose}><p className="muted">Create a temporary guest credential with a real Code 128 barcode.</p>{error&&<div className="alert error">{error}</div>}<form onSubmit={submit} className="form-grid"><label>Guest name<input value={f.visitor_name} onChange={e=>u('visitor_name',e.target.value)} required/></label><label>Contact<input value={f.contact_number} onChange={e=>u('contact_number',e.target.value)}/></label><label>Purpose<input value={f.purpose_of_visit} onChange={e=>u('purpose_of_visit',e.target.value)} required/></label><label>Plate<input value={f.plate_number} onChange={e=>u('plate_number',e.target.value.toUpperCase())}/></label><label>Vehicle<select value={f.vehicle_type} onChange={e=>u('vehicle_type',e.target.value)}><option>car</option><option>motorcycle</option><option>truck</option><option>tricycle</option><option>ebike</option><option>other</option></select></label><label>People<input type="number" min="1" max="20" value={f.people_count} onChange={e=>u('people_count',Number(e.target.value))}/></label><div className="full-width button-row"><button className="secondary" type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Creating…':'Create guest'}</button></div></form>{created&&<div className="credential"><span>Guest credential</span><strong>{created.visitor_id}</strong><Barcode value={created.visitor_id}/><button className="secondary compact" onClick={onDone}>Done</button></div>}</Modal>}

function BlacklistModal({onClose,onDone}){const [f,setF]=useState({visitor_name:'',plate_number:'',reason:'',start_date:'',end_date:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const u=(k,v)=>setF(x=>({...x,[k]:v}));async function submit(e){e.preventDefault();setBusy(true);try{const r=await api.post('/staff/blacklist',f);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to add blacklist entry.');onDone()}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}return <Modal title="Add blacklist entry" onClose={onClose}><p className="muted">Provide a guest name or plate number and a reason.</p>{error&&<div className="alert error">{error}</div>}<form onSubmit={submit} className="form-grid"><label>Guest name<input value={f.visitor_name} onChange={e=>u('visitor_name',e.target.value)}/></label><label>Plate number<input value={f.plate_number} onChange={e=>u('plate_number',e.target.value.toUpperCase())}/></label><label className="full-width">Reason<input value={f.reason} onChange={e=>u('reason',e.target.value)} required/></label><label>Start date<input type="date" value={f.start_date} onChange={e=>u('start_date',e.target.value)}/></label><label>End date<input type="date" value={f.end_date} onChange={e=>u('end_date',e.target.value)}/></label><div className="full-width button-row"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Add to blacklist'}</button></div></form></Modal>}

function OverrideModal({gate,onClose,onDone}){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[command,setCommand]=useState(null),[ack,setAck]=useState(false);async function request(){setBusy(true);try{const r=await api.post('/gate/override',{gate,emergency:true});if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Override failed.');setCommand(r.data)}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}async function acknowledge(){setBusy(true);try{const r=await api.post(`/gate/override/${command.command_id}/acknowledge`);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Acknowledgement failed.');setAck(true);onDone(gate)}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}return <Modal title={`${gate==='entry'?'Entry':'Exit'} gate emergency override`} onClose={onClose}><div className="danger-box"><strong>Emergency action</strong><p>The gate command will not reach the ESP32 until you acknowledge this emergency action.</p></div>{error&&<div className="alert error">{error}</div>}{!command?<div className="button-row"><button className="secondary" onClick={onClose}>Cancel</button><button className="danger" onClick={request} disabled={busy}>{busy?'Sending…':'Request gate opening'}</button></div>:<div className="ack-card"><strong>Override request created.</strong><p>Command #{command.command_id} is waiting for acknowledgement.</p><button className="danger" onClick={acknowledge} disabled={busy||ack}>{ack?'Acknowledged':'Acknowledge & open gate'}</button></div>}</Modal>}

function RfidPopup({event,onClose}){return <Modal title="RFID card scanned" onClose={onClose}><div className="rfid-popup"><div className="scan-icon">◉</div><div className="scan-row"><span>Gate</span><strong>{String(event.reader||'').toUpperCase()}</strong></div><div className="scan-row"><span>Account</span><strong>{event.account_name||event.account_email||'Unknown / unregistered'}</strong></div><div className="scan-row"><span>Vehicle plate</span><strong>{event.plate_number||'—'}</strong></div><div className="scan-row"><span>RFID</span><strong>{event.rfid_uid||'—'}</strong></div><div className={`decision ${event.gate_status}`}>{event.gate_status==='approved'?'GATE OPENED':'ACCESS DENIED'}</div><p className="muted">{event.log_notes||''}</p></div></Modal>}

function WalkInPanel({items,onAdd}){return <section className="panel"><PanelHead title="Walk-in guests" subtitle="Temporary guests created at the guard desk." action={<button className="primary compact" onClick={onAdd}>Add walk-in</button>}/><div className="table-wrap"><table><thead><tr><th>Credential</th><th>Name</th><th>Plate</th><th>Purpose</th><th>Status</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td><strong>{x.visitor_id}</strong></td><td>{x.visitor_name}</td><td>{x.plate_number||'—'}</td><td>{x.purpose_of_visit}</td><td><span className={`badge ${x.status}`}>{x.status}</span></td></tr>):<tr><td colSpan="5" className="empty">No walk-in guests.</td></tr>}</tbody></table></div></section>}
function BlacklistPanel({items,onAdd,onRemove}){return <section className="panel"><PanelHead title="Blacklist" subtitle="Active entries are checked during RFID and guest scans." action={<button className="primary compact" onClick={onAdd}>Add blacklist</button>}/><div className="table-wrap"><table><thead><tr><th>Guest</th><th>Plate</th><th>Reason</th><th>Status</th><th></th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td>{x.visitor_name||'—'}</td><td>{x.plate_number||'—'}</td><td>{x.reason}</td><td><span className={`badge ${x.status}`}>{x.status}</span></td><td>{x.status==='active'&&<button className="text-button" onClick={()=>onRemove(x.id)}>Deactivate</button>}</td></tr>):<tr><td colSpan="5" className="empty">No blacklist entries.</td></tr>}</tbody></table></div></section>}
function OverridePanel({onOpen}){return <section className="panel"><PanelHead title="Emergency gate override" subtitle="Every emergency opening requires an acknowledgement before the ESP32 receives it."/><div className="override-grid"><button className="danger large-control" onClick={()=>onOpen('entry')}>Open Entry Gate</button><button className="danger large-control" onClick={()=>onOpen('exit')}>Open Exit Gate</button></div></section>}
function AdminUsers({users}){return <section className="panel"><PanelHead title="Users" subtitle="Account status and roles."/><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Super admin</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.full_name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.status}</td><td>{u.is_super_admin?'Yes':'No'}</td></tr>)}</tbody></table></div></section>}
function AdminVehicles(){
    const [data,setData]=useState({resident_vehicles:[],staff_vehicles:[]}),[modal,setModal]=useState(false),[manageVehicle,setManageVehicle]=useState(null),[error,setError]=useState('');
    async function load(){try{const r=await api.get('/admin/account-vehicles');if(r.data?.ok)setData(r.data)}catch(e){setError(e.response?.data?.message||'Unable to load vehicles.')}}
    useEffect(()=>{load()},[]);
    return <section className="panel"><PanelHead title="Vehicles" subtitle="Resident and staff vehicles are managed separately." action={<button className="primary compact" onClick={()=>setModal(true)}>Add vehicle to account</button>}/>{error&&<div className="alert error">{error}</div>}<h3 className="section-title">Resident vehicles</h3><div className="table-wrap"><table><thead><tr><th>Account</th><th>Phase</th><th>Block-Lot-Letter</th><th>Plate</th><th>Type</th><th>Color</th><th>Manage</th></tr></thead><tbody>{data.resident_vehicles.length?data.resident_vehicles.map(v=><tr key={'r'+v.id}><td>{v.account_name}</td><td>{v.phase||'—'}</td><td>{[v.block_number,v.lot_number,v.household_letter].filter(Boolean).join('-')||'—'}</td><td>{v.plate_number}</td><td>{String(v.vehicle_type).toUpperCase()}</td><td>{v.color||'—'}</td><td><button className="secondary compact" onClick={()=>setManageVehicle({kind:'resident',...v})}>Manage</button></td></tr>):<tr><td colSpan="6" className="empty">No resident vehicles.</td></tr>}</tbody></table></div><h3 className="section-title">Staff vehicles</h3><div className="table-wrap"><table><thead><tr><th>Account</th><th>Role</th><th>Plate</th><th>Type</th><th>Color</th><th>Manage</th></tr></thead><tbody>{data.staff_vehicles.length?data.staff_vehicles.map(v=><tr key={'s'+v.id}><td>{v.account_name}</td><td>{v.role}</td><td>{v.plate_number}</td><td>{String(v.vehicle_type||'').toUpperCase()}</td><td>{v.color||'—'}</td><td><button className="secondary compact" onClick={()=>setManageVehicle({kind:'staff',...v})}>Manage</button></td></tr>):<tr><td colSpan="6" className="empty">No staff vehicles.</td></tr>}</tbody></table></div>{modal&&<AdminVehicleModal onClose={()=>setModal(false)} onDone={()=>{setModal(false);load()}}/>}{manageVehicle&&<AdminVehicleManageModal vehicle={manageVehicle} onClose={()=>setManageVehicle(null)} onDone={()=>{setManageVehicle(null);load()}}/>}</section>
}

function AdminVehicleManageModal({vehicle,onClose,onDone}){const [color,setColor]=useState(vehicle.color||''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function save(action){setBusy(true);setError('');try{const r=await api.post('/admin/vehicles/manage',{kind:vehicle.kind,id:vehicle.id,action,color});if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to update vehicle.');onDone()}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}return <Modal title={`Manage ${vehicle.plate_number}`} onClose={onClose}><div className="manage-vehicle-card"><div><span className="eyebrow">{String(vehicle.vehicle_type).toUpperCase()}</span><h3>{vehicle.account_name}</h3></div><label>Color<input value={color} onChange={e=>setColor(e.target.value)} required/></label></div>{error&&<div className="alert error">{error}</div>}<div className="button-row"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy} onClick={()=>save('update_color')}>Save color</button><button className="danger" disabled={busy} onClick={()=>{if(window.confirm(`Delete ${vehicle.plate_number}?`))save('delete')}}>Delete vehicle</button></div></Modal>}

function AdminVehicleModal({onClose,onDone}){
    const [accounts,setAccounts]=useState({residents:[],staff:[]}),[role,setRole]=useState('resident'),[phase,setPhase]=useState(''),[gateAssignment,setGateAssignment]=useState(''),[userId,setUserId]=useState(''),[plateMode,setPlateMode]=useState('standard'),[platePrefix,setPlatePrefix]=useState(''),[plateDigits,setPlateDigits]=useState(''),[f,setF]=useState({plate_number:'',vehicle_type:'car',color:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
    useEffect(()=>{api.get('/admin/accounts').then(r=>r.data?.ok&&setAccounts(r.data))},[]);
    const list=role==='resident'?accounts.residents.filter(a=>!phase||a.phase===phase):accounts.staff.filter(a=>(role==='admin'?a.role==='admin':a.role==='guard')&&(!gateAssignment||a.gate_assignment===gateAssignment));
    const phases=[...new Set(accounts.residents.map(a=>a.phase).filter(Boolean))];
    useEffect(()=>{setUserId('')},[role,phase,gateAssignment]);
    async function submit(e){e.preventDefault();setBusy(true);setError('');try{const payload={user_id:Number(userId),vehicle_type:f.vehicle_type,color:f.color};payload.plate_number=f.vehicle_type==='ebike'?null:(plateMode==='standard'?`${platePrefix.toUpperCase()} ${plateDigits}`.trim():f.plate_number.toUpperCase());const r=await api.post('/admin/vehicles',payload);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to add vehicle.');onDone()}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}
    return <Modal title="Add vehicle to account" onClose={onClose}><p className="muted">Choose the account first, then add the vehicle.</p>{error&&<div className="alert error">{error}</div>}<form className="form-stack" onSubmit={submit}><label>Account role<select value={role} onChange={e=>setRole(e.target.value)}><option value="resident">Resident</option><option value="guard">Guard</option><option value="admin">Admin</option></select></label>{role==='resident'&&<label>Phase<select value={phase} onChange={e=>setPhase(e.target.value)}><option value="">All phases</option>{phases.map(p=><option key={p}>{p}</option>)}</select></label>}{role==='guard'&&<label>Gate assignment<select value={gateAssignment} onChange={e=>setGateAssignment(e.target.value)}><option value="">All gate assignments</option><option>1</option><option>2</option><option>3</option></select></label>}<label>Account<select value={userId} onChange={e=>setUserId(e.target.value)} required><option value="">Select account</option>{list.map(a=><option key={a.id} value={a.id}>{a.full_name} — {a.email}{a.gate_assignment?` — ${a.gate_assignment}`:''}</option>)}</select></label><label>Vehicle type<select value={f.vehicle_type} onChange={e=>setF({...f,vehicle_type:e.target.value})}>{['car','motorcycle','truck','tricycle','ebike','other'].map(x=><option key={x}>{x.toUpperCase()}</option>)}</select></label>{f.vehicle_type==='ebike'?<div className="full-width alert"><strong>E-bike plate generated automatically.</strong><p className="muted">A unique plate in the XXXX 1111 format will be assigned when you save.</p></div>:<><div className="segmented two"><button type="button" className={plateMode==='standard'?'selected':''} onClick={()=>setPlateMode('standard')}>Standard plate</button><button type="button" className={plateMode==='custom'?'selected':''} onClick={()=>setPlateMode('custom')}>Custom plate</button></div>{plateMode==='standard'?<div className="form-grid"><label>Letters (XXX)<input value={platePrefix} maxLength={3} onChange={e=>setPlatePrefix(e.target.value.replace(/[^A-Za-z]/g,'').toUpperCase())} required/></label><label>Numbers (1111)<input value={plateDigits} maxLength={4} onChange={e=>setPlateDigits(e.target.value.replace(/\D/g,'').slice(0,4))} required/></label></div>:<label>Custom plate<input value={f.plate_number} onChange={e=>setF({...f,plate_number:e.target.value.toUpperCase()})} required/></label>}</>}<label>Color<input value={f.color} onChange={e=>setF({...f,color:e.target.value})} required/></label><div className="button-row"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy||!userId}>{busy?'Saving…':'Add vehicle'}</button></div></form></Modal>
}
function AdminAccounts(){
    const [data,setData]=useState({residents:[],staff:[]}),[manage,setManage]=useState(null),[create,setCreate]=useState(false),[error,setError]=useState(''),[residentPage,setResidentPage]=useState(1),[staffPage,setStaffPage]=useState(1);
    async function load(){try{const r=await api.get('/admin/accounts');if(r.data?.ok)setData(r.data)}catch(e){setError(e.response?.data?.message||'Unable to load accounts.')}}
    useEffect(()=>{load()},[]);
    return <section className="panel"><PanelHead title="Accounts" subtitle="Residents and staff are managed separately." action={<button className="primary compact" onClick={()=>setCreate(true)}>Add account</button>}/><p className="muted">Resident accounts are sortable by Phase, then Block, Lot and Letter.</p>{error&&<div className="alert error">{error}</div>}<h3 className="section-title">Resident accounts</h3><div className="table-wrap"><table><thead><tr><th>Name</th><th>Username</th><th>Phase</th><th>Block-Lot-Letter</th><th>Email</th><th>Status</th><th>Manage</th></tr></thead><tbody>{paginate(data.residents,residentPage,20).map(u=><tr key={u.id}><td>{u.full_name}</td><td>{u.username||'—'}</td><td>{u.phase||'—'}</td><td>{[u.block_number,u.lot_number,u.household_letter].filter(Boolean).join('-')||u.house_number}</td><td>{u.email}</td><td><span className={`badge ${u.locked_until?'offline':u.status}`}>{u.locked_until?'Locked':u.status}</span></td><td><button className="secondary compact" onClick={()=>setManage(u)}>Manage</button></td></tr>)}</tbody></table></div><Pagination page={residentPage} total={data.residents.length} pageSize={20} onPage={setResidentPage}/><h3 className="section-title">Staff accounts</h3><div className="table-wrap"><table><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Gate assignment</th><th>Email</th><th>Status</th><th>Manage</th></tr></thead><tbody>{paginate(data.staff,staffPage,20).map(u=><tr key={u.id}><td>{u.full_name}</td><td>{u.username||'—'}</td><td>{u.role}</td><td>{u.gate_assignment||'—'}</td><td>{u.email}</td><td><span className={`badge ${u.locked_until?'offline':u.status}`}>{u.locked_until?'Locked':u.status}</span></td><td><button className="secondary compact" onClick={()=>setManage(u)}>Manage</button></td></tr>)}</tbody></table></div><Pagination page={staffPage} total={data.staff.length} pageSize={20} onPage={setStaffPage}/>{manage&&<AccountManageModal account={manage} onClose={()=>setManage(null)} onDone={()=>{setManage(null);load()}}/>}{create&&<CreateAccountModal onClose={()=>setCreate(false)} onDone={(result)=>{setCreate(false);load();window.alert(`Account created. Temporary password: ${result.temporary_password}`)}}/>}</section>
}
function CreateAccountModal({onClose,onDone}){
    const [role,setRole]=useState('resident'),[f,setF]=useState({full_name:'',email:'',username:'',phase:'',block:'',lot:'',letter:'',gate:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
    async function submit(e){e.preventDefault();setBusy(true);setError('');try{const payload={full_name:f.full_name,email:f.email,username:f.username,role};if(role==='resident')Object.assign(payload,{phase:f.phase,block_number:f.block,lot_number:f.lot,household_letter:f.letter.toUpperCase()});if(role==='guard')payload.gate_assignment=f.gate;const r=await api.post('/admin/accounts',payload);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to create account.');onDone(r.data)}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}
    return <Modal title="Add account" onClose={onClose}><p className="muted">A temporary password is generated automatically and shown once after creation.</p>{error&&<div className="alert error">{error}</div>}<form className="form-grid" onSubmit={submit}><label>Account owner name<input value={f.full_name} onChange={e=>setF({...f,full_name:e.target.value})} required/></label><label>Email<input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} required/></label><label>Username<input value={f.username} onChange={e=>setF({...f,username:e.target.value.replace(/[^A-Za-z0-9._-]/g,'')})} required/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="resident">Resident</option><option value="guard">Guard</option><option value="admin">Admin</option></select></label>{role==='resident'&&<><label>Phase<input value={f.phase} onChange={e=>setF({...f,phase:e.target.value.replace(/\D/g,'').slice(0,3)})} placeholder="1" required/></label><label>Block<input value={f.block} onChange={e=>setF({...f,block:e.target.value.replace(/\D/g,'')})} required/></label><label>Lot<input value={f.lot} onChange={e=>setF({...f,lot:e.target.value.replace(/\D/g,'')})} required/></label><label>Letter<input maxLength={1} value={f.letter} onChange={e=>setF({...f,letter:e.target.value.replace(/[^A-Za-z]/g,'').toUpperCase()})} required/></label></>}{role==='guard'&&<label>Gate assignment<select value={f.gate} onChange={e=>setF({...f,gate:e.target.value})} required><option value="">Select gate</option><option>1</option><option>2</option><option>3</option></select></label>}<div className="full-width alert">Resident address is stored as Block-Lot-Letter with no spaces, e.g. 12-4-A.</div><div className="full-width button-row"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Creating…':'Create account'}</button></div></form></Modal>
}
function AccountManageModal({account,onClose,onDone}){
    const [action,setAction]=useState('password'),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
    const locked=account.locked_until && new Date(account.locked_until).getTime()>Date.now();
    async function submit(){setBusy(true);setError('');try{if(action==='delete'){if(account.is_super_admin)return;if(!window.confirm(`Delete ${account.full_name}? This cannot be undone.`))return;const r=await api.post(`/admin/accounts/${account.id}/delete`);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Delete failed.')}else if(action==='lock'||action==='unlock'){const r=await api.post(`/admin/accounts/${account.id}/${action}`);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to change account lock.')}else{const r=await api.post(`/admin/accounts/${account.id}/${action}`,action==='email'?{email:value}:{password:value});if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Update failed.')}onDone()}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}
    return <div className="account-manage-modal"><Modal title={`Manage ${account.full_name}`} onClose={onClose}><div className="manage-account-surface"><div className="account-summary"><span className="eyebrow">{String(account.role).toUpperCase()}</span><strong>{account.email}</strong><span className={`badge ${locked?'offline':'online'}`}>{locked?'Locked':'Available'}</span></div><div className="segmented manage-actions"><button className={action==='password'?'selected':''} onClick={()=>setAction('password')}>Password</button><button className={action==='email'?'selected':''} onClick={()=>setAction('email')}>Email</button><button className={action==='lock'?'selected':''} onClick={()=>setAction(locked?'unlock':'lock')}>{locked?'Unlock':'Lock 1 hour'}</button>{!account.is_super_admin&&<button className={action==='delete'?'selected danger-selected':''} onClick={()=>setAction('delete')}>Delete</button>}</div>{error&&<div className="alert error">{error}</div>}{action==='password'&&<label>New password<input type="password" value={value} onChange={e=>setValue(e.target.value)} minLength={8} required/></label>}{action==='email'&&<label>New email<input type="email" value={value} onChange={e=>setValue(e.target.value)} required/></label>}{action==='lock'&&<div className="settings-card"><h3>Lock this account for 1 hour?</h3><p className="muted">The account will be unable to log in until an admin unlocks it or the hour expires.</p></div>}{action==='unlock'&&<div className="settings-card"><h3>Unlock this account?</h3><p className="muted">The account can sign in immediately.</p></div>}{action==='delete'&&<div className="danger-box"><strong>Delete account</strong><p>This permanently removes the account. KUN3H0 cannot be deleted.</p></div>}<div className="button-row"><button className="secondary" onClick={onClose}>Cancel</button><button className={action==='delete'?'danger':'primary'} disabled={busy||((action==='password'||action==='email')&&!value)} onClick={submit}>{busy?'Saving…':action==='delete'?'Delete account':action==='lock'?'Lock account':action==='unlock'?'Unlock account':'Save'}</button></div></div></Modal></div>
}
function AdminRfid(){return <section className="panel"><PanelHead title="RFID" subtitle="RFID management is reserved for a later release."/><div className="empty feature-placeholder"><strong>To be added.</strong><p className="muted">RFID card assignment and management will be added here.</p></div></section>}
function AccountLogTable({logs}){return <div className="table-wrap"><table><thead><tr><th>Time (GMT+8)</th><th>Account</th><th>Role</th><th>Action</th><th>Details</th></tr></thead><tbody>{logs.length?logs.map(x=><tr key={x.id}><td>{manilaTime(x.created_at)}</td><td>{x.full_name||x.account_identifier||x.email}</td><td>{x.role||x.account_type}</td><td>{String(x.action).replaceAll('_',' ')}</td><td>{x.details||'—'}</td></tr>):<tr><td colSpan="5" className="empty">No account activity.</td></tr>}</tbody></table></div>}

function AccountSettings({onPasswordChanged}){
    const [f,setF]=useState({current_password:'',new_password:'',new_password_confirmation:''}),[error,setError]=useState(''),[ok,setOk]=useState(''),[busy,setBusy]=useState(false);
    async function submit(e){e.preventDefault();setError('');setOk('');setBusy(true);try{const r=await api.post('/auth/change-password',f);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to change password.');if(r.data.token)localStorage.setItem('smart-gate-auth-token',r.data.token);setF({current_password:'',new_password:'',new_password_confirmation:''});setOk('Password changed successfully.')}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}
    return <section className="panel settings-panel"><PanelHead title="Account settings" subtitle="Manage your account security."/><div className="settings-card"><h3>Change password</h3><p className="muted">Use a strong password you do not reuse elsewhere.</p>{error&&<div className="alert error">{error}</div>}{ok&&<div className="alert success">{ok}</div>}<form className="form-grid" onSubmit={submit}><label>Current password<input type="password" value={f.current_password} onChange={e=>setF({...f,current_password:e.target.value})} required/></label><label>New password<input type="password" minLength={8} value={f.new_password} onChange={e=>setF({...f,new_password:e.target.value})} required/></label><label>Confirm new password<input type="password" minLength={8} value={f.new_password_confirmation} onChange={e=>setF({...f,new_password_confirmation:e.target.value})} required/></label><div className="full-width button-row"><button className="primary" disabled={busy}>{busy?'Saving…':'Change password'}</button></div></form></div></section>}

function ResidentVehicleModal({onClose,onDone}){
    const [f,setF]=useState({plate_number:'',vehicle_type:'car',color:''}),[plateMode,setPlateMode]=useState('standard'),[prefix,setPrefix]=useState(''),[digits,setDigits]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
    async function submit(e){e.preventDefault();setBusy(true);setError('');try{const plate=f.vehicle_type==='ebike'?null:(plateMode==='standard'?`${prefix.toUpperCase()} ${digits}`.trim():f.plate_number.toUpperCase());const r=await api.post('/vehicles',{vehicle_type:f.vehicle_type,color:f.color,plate_number:plate});if(r.status>=300)throw new Error(r.data?.message||'Unable to add vehicle.');onDone()}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}
    return <Modal title="Add vehicle" onClose={onClose}><p className="muted">Residents may register up to 20 vehicles.</p>{error&&<div className="alert error">{error}</div>}<form className="form-grid" onSubmit={submit}><label>Vehicle type<select value={f.vehicle_type} onChange={e=>setF({...f,vehicle_type:e.target.value})}>{['car','motorcycle','truck','tricycle','ebike','other'].map(x=><option key={x}>{x.toUpperCase()}</option>)}</select></label>{f.vehicle_type==='ebike'?<div className="full-width alert"><strong>E-bike plate generated automatically.</strong><p className="muted">A unique plate in the XXXX 1111 format will be assigned when you save.</p></div>:<><div className="full-width segmented two"><button type="button" className={plateMode==='standard'?'selected':''} onClick={()=>setPlateMode('standard')}>Standard plate</button><button type="button" className={plateMode==='custom'?'selected':''} onClick={()=>setPlateMode('custom')}>Custom plate</button></div>{plateMode==='standard'?<><label>Letters (XXX)<input value={prefix} maxLength={3} onChange={e=>setPrefix(e.target.value.replace(/[^A-Za-z]/g,'').toUpperCase())} required/></label><label>Numbers (1111)<input value={digits} maxLength={4} onChange={e=>setDigits(e.target.value.replace(/\D/g,'').slice(0,4))} required/></label></>:<label>Custom plate<input value={f.plate_number} onChange={e=>setF({...f,plate_number:e.target.value.toUpperCase()})} required/></label>}</>}<label>Color<input value={f.color} onChange={e=>setF({...f,color:e.target.value})} required/></label><div className="full-width button-row"><button className="secondary" type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Add vehicle'}</button></div></form></Modal>}
function ResidentRequests({requests,onDelete}){return <section className="panel"><PanelHead title="Guest requests" subtitle="Active guest requests can be deleted here. Guest history is kept separately and cannot be deleted."/><div className="table-wrap"><table><thead><tr><th>Guest</th><th>Credential</th><th>Visit vehicles</th><th>Status</th><th></th></tr></thead><tbody>{requests.length?requests.map(x=><tr key={x.id}><td>{x.visitor_name}</td><td>{x.visitor_id||'—'}</td><td>{x.vehicle_count||1}</td><td><span className={`badge ${x.status}`}>{x.status}</span></td><td><button className="text-button danger-text" onClick={()=>onDelete(x)}>Delete</button></td></tr>):<tr><td colSpan="5" className="empty">No guest requests.</td></tr>}</tbody></table></div></section>}

function PreRegisterVisitorModal({onClose,onDone}){
    const [f,setF]=useState({visitor_name:'',contact_number:'',purpose_of_visit:'',people_count:1,stay_days:1,vehicles:[{plate_number:'',vehicle_type:'car'}]}),[idFile,setIdFile]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null);
    const updateVehicle=(i,k,v)=>setF(x=>({...x,vehicles:x.vehicles.map((a,n)=>n===i?{...a,[k]:v}:a)}));
    function addVehicle(){if(f.vehicles.length<10)setF(x=>({...x,vehicles:[...x.vehicles,{plate_number:'',vehicle_type:'car'}]}))}
    function removeVehicle(i){setF(x=>({...x,vehicles:x.vehicles.filter((_,n)=>n!==i)}))}
    async function submit(e){e.preventDefault();setBusy(true);setError('');try{const fd=new FormData();fd.append('visitor_name',f.visitor_name);fd.append('contact_number',f.contact_number);fd.append('purpose_of_visit',f.purpose_of_visit);fd.append('people_count',String(f.people_count));fd.append('stay_days',String(f.stay_days));f.vehicles.forEach((v,i)=>{fd.append(`vehicles[${i}][plate_number]`,v.plate_number.toUpperCase());fd.append(`vehicles[${i}][vehicle_type]`,v.vehicle_type)});if(idFile)fd.append('government_id',idFile);const r=await api.post('/resident/visitors',fd);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to pre-register guest.');setResult(r.data);onDone(r.data)}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}
    if(result)return <Modal title="Guest registered" onClose={onClose}><p className="muted">Automatically approved. Give the guest the six-character code and barcode.</p><div className="credential"><span>Six-character code</span><strong>{result.visitor_id}</strong><Barcode value={result.visitor_id}/></div><button className="primary btn-block" onClick={onClose}>Done</button></Modal>;
    return <Modal title="Pre-register guest" onClose={onClose} wide><p className="muted">You are registering this guest yourself, so approval is automatic.</p>{error&&<div className="alert error">{error}</div>}<form className="form-grid" onSubmit={submit}><label>Guest name<input value={f.visitor_name} onChange={e=>setF({...f,visitor_name:e.target.value})} required/></label><label>Contact number<input value={f.contact_number} onChange={e=>setF({...f,contact_number:e.target.value})}/></label><label>Purpose<input value={f.purpose_of_visit} onChange={e=>setF({...f,purpose_of_visit:e.target.value})} required/></label><label>How many days are they staying?<input type="number" min="1" max="30" value={f.stay_days} onChange={e=>setF({...f,stay_days:Number(e.target.value)})} required /></label><label>People count<input type="number" min="1" max="20" value={f.people_count} onChange={e=>setF({...f,people_count:Number(e.target.value)})}/></label><div className="full-width"><div className="panel-head"><div><h3>Vehicles</h3><p className="muted">Up to 10 vehicles.</p></div><button type="button" className="secondary compact" onClick={addVehicle} disabled={f.vehicles.length>=10}>Add vehicle</button></div>{f.vehicles.map((v,i)=><div className="vehicle-row" key={i}><input placeholder="Plate number" value={v.plate_number} onChange={e=>updateVehicle(i,'plate_number',e.target.value.toUpperCase())} required/><select value={v.vehicle_type} onChange={e=>updateVehicle(i,'vehicle_type',e.target.value)}><option>car</option><option>motorcycle</option><option>truck</option><option>tricycle</option><option>ebike</option><option>other</option></select>{i>0&&<button type="button" className="text-button" onClick={()=>removeVehicle(i)}>Remove</button>}</div>)}</div><label className="full-width">Government ID (optional)<input type="file" accept=".jpg,.jpeg,.png,.pdf" onChange={e=>setIdFile(e.target.files?.[0]||null)}/></label><div className="full-width button-row"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Registering…':'Register guest'}</button></div></form></Modal>
}

function ResidentDashboard({user,onLogout}) {
    const [active,setActive]=useState('overview'),[collapsed,setCollapsed]=useState(() => localStorage.getItem('smart-gate-sidebar') === 'mini'),[vehicles,setVehicles]=useState([]),[requests,setRequests]=useState([]),[notifications,setNotifications]=useState([]),[error,setError]=useState(''),[modal,setModal]=useState(null);
    async function load(){try{const [v,r]=await Promise.all([api.get('/vehicles'),api.get('/resident/visitor-requests')]);if(v.status<300)setVehicles(v.data.vehicles||v.data||[]);if(r.status<300){setRequests(r.data.requests||[]); if(r.data.unread_count>0){const n=await api.get('/resident/notifications'); if(n.status<300)setNotifications(n.data.notifications||[]);}}}catch(e){setError(e.response?.data?.message||'Unable to load resident data.')}}
    useEffect(()=>{load();const t=setInterval(load,8000);return()=>clearInterval(t)},[]);async function deleteRequest(request){if(!window.confirm(`Delete the guest request for ${request.visitor_name}? It will remain in Guest History.`))return;try{const r=await api.delete(`/resident/visitor-requests/${request.id}`);if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to delete guest request.');await load()}catch(e){setError(e.response?.data?.message||e.message)}}
    async function logout(){try{await api.post('/auth/logout')}finally{onLogout()}}
    const nav=navFor(user.role);
    return <Shell dashboard user={user} onHome={()=>setActive('overview')} onLogout={logout}><Sidebar user={user} active={active} setActive={setActive} collapsed={collapsed} setCollapsed={setCollapsed}/><main className={`dashboard-page ${collapsed ? 'sidebar-collapsed' : ''}`}><div className="mobile-sticky-nav">{nav.map(i=><button key={i.id} className={active===i.id?'active':''} onClick={()=>setActive(i.id)}><span>{i.icon}</span><small>{i.label}</small></button>)}</div><div className="dashboard-content">{error&&<div className="alert error">{error}</div>}{active==='overview'?<><section className="dashboard-head"><div><p className="eyebrow">RESIDENT DASHBOARD</p><h1>Welcome, {user.full_name}</h1><p className="muted">{user.email}</p><p className="muted resident-location">Phase {user.phase||'—'} · {user.house_number||'—'}</p></div></section>{notifications.filter(n=>!n.is_read).map(n=><div key={n.id} className="alert guest-notification"><strong>{n.title}</strong><span>{n.message}</span><button className="text-button" onClick={async()=>{await api.post(`/resident/notifications/${n.id}/read`);load()}}>Mark read</button></div>)}<section className="feature-grid resident-preregister-top"><FeatureCard title="Pre-register guest" text="Register a guest yourself. Approval is automatic and you receive a barcode plus six-character code." button="Register guest" onClick={()=>setModal('pre-register')}/></section><div className="stats"><Stat label="My vehicles" value={vehicles.length}/><Stat label="Registered guests" value={requests.filter(r=>r.status==='approved').length}/></div><ResidentRequests requests={requests} onDelete={deleteRequest}/></>:active==='vehicles'?<section className="panel"><PanelHead title="My vehicles" subtitle="Vehicles associated with your resident account." action={<button className="primary compact" onClick={()=>setModal('vehicle')}>Add vehicle</button>}/><div className="table-wrap"><table><thead><tr><th>Plate</th><th>Type</th><th>Color</th><th>Status</th><th></th></tr></thead><tbody>{vehicles.map(v=><tr key={v.id}><td>{v.plate_number}</td><td>{v.vehicle_type}</td><td>{v.color||'—'}</td><td>{v.status||'active'}</td><td><button className="text-button" onClick={async()=>{await api.delete(`/vehicles/${v.id}`);load()}}>Remove</button></td></tr>)}</tbody></table></div></section>:active==='guest-history'?<GuestHistory/>:active==='settings'?<AccountSettings/>:<ResidentRequests requests={requests} onDelete={deleteRequest}/>}</div></main>{modal==='vehicle'&&<ResidentVehicleModal onClose={()=>setModal(null)} onDone={()=>{setModal(null);load()}}/>}{modal==='pre-register'&&<PreRegisterVisitorModal onClose={()=>{setModal(null);load()}} onDone={()=>{load()}}/>}</Shell>
}

function GuestHistory(){
    const [data,setData]=useState({guests:[],gate_events:[]}),[error,setError]=useState('');
    async function load(){try{const r=await api.get('/resident/guest-history');if(r.status>=300||!r.data?.ok)throw new Error(r.data?.message||'Unable to load guest history.');setData(r.data)}catch(e){setError(e.response?.data?.message||e.message)}}
    useEffect(()=>{load()},[]);
    return <section className="panel"><PanelHead title="Guest history" subtitle="Previous guest registrations, credential validity and gate activity."/>{error&&<div className="alert error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Guest</th><th>Credential</th><th>Stay</th><th>Status</th><th>Expires</th><th>Registered</th><th></th></tr></thead><tbody>{data.guests.length?data.guests.map(g=><tr key={g.id}><td>{g.visitor_name}</td><td>{g.visitor_id||'—'}</td><td>{g.stay_days||1} day(s)</td><td><span className={`badge ${g.status}`}>{g.status}</span></td><td>{g.expires_at?manilaTime(g.expires_at):'—'}</td><td>{manilaTime(g.created_at)}</td><td>{['pending','approved'].includes(g.status)?<button className="text-button danger-text" onClick={async()=>{if(window.confirm('Revoke this guest credential now?')){const r=await api.post(`/resident/guest/${g.id}/revoke`);if(r.status<300)load();else alert(r.data?.message||'Unable to revoke guest.')}}}>Revoke</button>: '—'}</td></tr>):<tr><td colSpan="7" className="empty">No guest history yet.</td></tr>}</tbody></table></div><h3 className="section-title">Gate events</h3><LogTable logs={data.gate_events||[]}/></section>
}

function App(){
    const [view,setView]=useState('home'),[user,setUser]=useState(null);
    useEffect(()=>{api.get('/auth/me').then(r=>{if(r.status===200&&r.data?.user){setUser(r.data.user);setView('dashboard')}}).catch(()=>{})},[]);
    function navigate(next){setView(next);window.history.replaceState({},'',next==='home'?'/':`/${next}`)}
    function loggedIn(u){setUser(u);setView('dashboard');window.history.replaceState({},'','/dashboard')}
    function loggedOut(){localStorage.removeItem('smart-gate-auth-token');setUser(null);navigate('home')}
    if(user) return user.role==='resident'?<ResidentDashboard user={user} onLogout={loggedOut}/>:<StaffDashboard user={user} onLogout={loggedOut}/>;
    if(view==='login') return <Login navigate={navigate} onLogin={loggedIn}/>;
    if(view==='visitor') return <Visitor navigate={navigate}/>;
    if(view==='status') return <VisitorStatus navigate={navigate}/>;
    return <Landing navigate={navigate}/>;
}

createRoot(document.getElementById('root')).render(<App />);
